image: gcc
before_script:
   - apt-get update --yes
   - apt-get install --yes cmake
   - apt-get install --yes libprotobuf-dev protobuf-compiler

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_linux:
   stage: build
   script:
      - mkdir build
      - cd build
      - cmake ..
      - make

